# cm_use_eigen3()
# Eigen3 is a header-only library
function(cm_use_eigen3)
    if (VCPKG_TOOLCHAIN)
        find_package(Eigen3 CONFIG REQUIRED)
    else()
        include("${GE_PACKAGES_DIR}/share/eigen3/Eigen3Config.cmake")
    endif()

    target_link_libraries(${__CurrentTargetName__} PRIVATE Eigen3::Eigen)
endfunction()

# cm_use_nlohmann_json()
# nlohmann_json is a header-only library
function(cm_use_nlohmann_json)
    if (VCPKG_TOOLCHAIN)
        find_package(nlohmann_json CONFIG REQUIRED)
    else()
        include("${GE_PACKAGES_DIR}/share/nlohmann_json/nlohmann_jsonConfig.cmake")
    endif()

    target_link_libraries(${__CurrentTargetName__} PRIVATE nlohmann_json::nlohmann_json)
endfunction()

# cm_use_tinygltf()
function(cm_use_tinygltf)
    # there is no CMake targets provided by VCPKG_TOOLCHAIN
    add_library(tinygltf::tinygltf INTERFACE IMPORTED GLOBAL)
    target_include_directories(tinygltf::tinygltf INTERFACE "${GE_PACKAGES_DIR}/include")
    foreach(file "stb_image.h" "nlohmann/json.hpp")
        if (NOT EXISTS "${GE_PACKAGES_DIR}/include/${file}")
            message(FATAL_ERROR "header file dependency(${file}) does not exist")
        endif()
    endforeach()

    target_link_libraries(${__CurrentTargetName__} PRIVATE tinygltf::tinygltf)
endfunction()

# cm_use_glfw3()
function(cm_use_glfw3)
    if (VCPKG_TOOLCHAIN)
        find_package(glfw3 CONFIG REQUIRED)
    else()
        include("${GE_PACKAGES_DIR}/share/glfw3/glfw3Config.cmake")
        string(TOLOWER "${CMAKE_BUILD_TYPE}" _buildTypeLower)
        if ("${_buildTypeLower}" STREQUAL "debug")
            include("${GE_PACKAGES_DIR}/share/glfw3/glfw3Targets-debug.cmake")
        else()
            include("${GE_PACKAGES_DIR}/share/glfw3/glfw3Targets-release.cmake")
        endif()
    endif()

    target_link_libraries(${__CurrentTargetName__} PRIVATE glfw)
endfunction()

# cm_use_imgui()
function(cm_use_imgui)
    if (VCPKG_TOOLCHAIN)
        find_package(imgui CONFIG REQUIRED)
    else()
        include("${GE_PACKAGES_DIR}/share/imgui/imguiConfig.cmake")
        string(TOLOWER "${CMAKE_BUILD_TYPE}" _buildTypeLower)
        if ("${_buildTypeLower}" STREQUAL "debug")
            include("${GE_PACKAGES_DIR}/share/imgui/imguiConfig-debug.cmake")
        else()
            include("${GE_PACKAGES_DIR}/share/imgui/imguiConfig-release.cmake")
        endif()
    endif()

    target_link_libraries(${__CurrentTargetName__} PRIVATE imgui::imgui)
endfunction()

# cm_use_tinyobjloader()
function(cm_use_tinyobjloader)
    if (VCPKG_TOOLCHAIN)
        find_package(tinyobjloader CONFIG REQUIRED)
    else()
        include("${GE_PACKAGES_DIR}/share/tinyobjloader/tinyobjloader-config.cmake")
        string(TOLOWER "${CMAKE_BUILD_TYPE}" _buildTypeLower)
        if ("${_buildTypeLower}" STREQUAL "debug")
            include("${GE_PACKAGES_DIR}/share/tinyobjloader/tinyobjloader-targets-debug.cmake")
        else()
            include("${GE_PACKAGES_DIR}/share/tinyobjloader/tinyobjloader-targets-release.cmake")
        endif()
    endif()

    target_link_libraries(${__CurrentTargetName__} PRIVATE tinyobjloader::tinyobjloader)
endfunction()

# cm_use_gtest()
function(cm_use_gtest)
    if (VCPKG_TOOLCHAIN)
        find_package(GTest CONFIG REQUIRED)
    else()
        include("${GE_PACKAGES_DIR}/share/gtest/GTestConfig.cmake")
        string(TOLOWER "${CMAKE_BUILD_TYPE}" _buildTypeLower)
        if ("${_buildTypeLower}" STREQUAL "debug")
            include("${GE_PACKAGES_DIR}/share/gtest/GTestTargets-debug.cmake")
        else()
            include("${GE_PACKAGES_DIR}/share/gtest/GTestTargets-release.cmake")
        endif()
    endif()

    target_link_libraries(${__CurrentTargetName__} PRIVATE GTest::gtest GTest::gmock)
endfunction()