#include "RHI/Formats.h"
#include "Framework.h"

namespace GS
{
	const FormatDesc kFormatDescArray[] =
	{
		// Format                              Name,        BytesPerBlock    ChannelCount          Type             bDepth,    bStencil,  bCompressed,   CompressionRatioWidth,     CompressionRatioHeight
		{ EResourceFormat::Unknown,            "Unknown",          0,              0,        EFormatType::Unknown,    false,     false,     false,        1, 1 },
		{ EResourceFormat::R8Unorm,            "R8Unorm",          1,              1,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R8Snorm,            "R8Snorm",          1,              1,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Unorm,           "R16Unorm",         2,              1,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Snorm,           "R16Snorm",         2,              1,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG8Unorm,           "RG8Unorm",         2,              2,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG8Snorm,           "RG8Snorm",         2,              2,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Unorm,          "RG16Unorm",        4,              2,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Snorm,          "RG16Snorm",        4,              2,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Unorm,         "RGB16Unorm",       6,              3,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Snorm,         "RGB16Snorm",       6,              3,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R24UnormX8,         "R24UnormX8",       4,              1,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB5A1Unorm,        "RGB5A1Unorm",      2,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8Unorm,         "RGBA8Unorm",       4,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8Snorm,         "RGBA8Snorm",       4,              4,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB10A2Unorm,       "RGB10A2Unorm",     4,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB10A2Uint,        "RGB10A2Uint",      4,              4,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA16Unorm,        "RGBA16Unorm",      8,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8UnormSrgb,     "RGBA8UnormSrgb",   4,              4,        EFormatType::UnormSrgb,  false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Float,           "R16Float",         2,              1,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Float,          "RG16Float",        4,              2,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Float,         "RGB16Float",       6,              3,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA16Float,        "RGBA16Float",      8,              4,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R32Float,           "R32Float",         4,              1,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R32FloatX32,        "R32FloatX32",      4,              1,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG32Float,          "RG32Float",        8,              2,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB32Float,         "RGB32Float",      12,              3,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA32Float,        "RGBA32Float",     16,              4,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R11G11B10Float,     "R11G11B10Float",   4,              3,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB9E5Float,        "RGB9E5Float",      4,              3,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R8Int,              "R8Int",            1,              1,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R8Uint,             "R8Uint",           1,              1,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Int,             "R16Int",           2,              1,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Uint,            "R16Uint",          2,              1,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R32Int,             "R32Int",           4,              1,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R32Uint,            "R32Uint",          4,              1,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG8Int,             "RG8Int",           2,              2,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG8Uint,            "RG8Uint",          2,              2,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Int,            "RG16Int",          4,              2,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Uint,           "RG16Uint",         4,              2,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG32Int,            "RG32Int",          8,              2,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG32Uint,           "RG32Uint",         8,              2,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Int,           "RGB16Int",         6,              3,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Uint,          "RGB16Uint",        6,              3,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB32Int,           "RGB32Int",        12,              3,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB32Uint,          "RGB32Uint",       12,              3,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8Int,           "RGBA8Int",         4,              4,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8Uint,          "RGBA8Uint",        4,              4,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA16Int,          "RGBA16Int",        8,              4,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA16Uint,         "RGBA16Uint",       8,              4,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA32Int,          "RGBA32Int",       16,              4,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA32Uint,         "RGBA32Uint",      16,              4,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::BGRA8Unorm,         "BGRA8Unorm",       4,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::BGRA8UnormSrgb,     "BGRA8UnormSrgb",   4,              4,        EFormatType::UnormSrgb,  false,     false,     false,        1, 1 },
		{ EResourceFormat::BGRX8Unorm,         "BGRX8Unorm",       4,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::BGRX8UnormSrgb,     "BGRX8UnormSrgb",   4,              4,        EFormatType::UnormSrgb,  false,     false,     false,        1, 1 },
		{ EResourceFormat::Alpha8Unorm,        "Alpha8Unorm",      1,              1,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::Alpha32Float,       "Alpha32Float",     4,              1,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R5G6B5Unorm,        "R5G6B5Unorm",      2,              3,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::D32Float,           "D32Float",         4,              1,        EFormatType::Float,       true,     false,     false,        1, 1 },
		{ EResourceFormat::D16Unorm,           "D16Unorm",         2,              1,        EFormatType::Unorm,       true,     false,     false,        1, 1 },
		{ EResourceFormat::D32FloatS8X24,      "D32FloatS8X24",    8,              2,        EFormatType::Float,       true,      true,     false,        1, 1 },
		{ EResourceFormat::D24UnormS8,         "D24UnormS8",       4,              2,        EFormatType::Unorm,       true,      true,     false,        1, 1 },
		{ EResourceFormat::BC1Unorm,           "BC1Unorm",         8,              3,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC1UnormSrgb,       "BC1UnormSrgb",     8,              3,        EFormatType::UnormSrgb,  false,     false,      true,        4, 4 },
		{ EResourceFormat::BC2Unorm,           "BC2Unorm",        16,              4,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC2UnormSrgb,       "BC2UnormSrgb",    16,              4,        EFormatType::UnormSrgb,  false,     false,      true,        4, 4 },
		{ EResourceFormat::BC3Unorm,           "BC3Unorm",        16,              4,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC3UnormSrgb,       "BC3UnormSrgb",    16,              4,        EFormatType::UnormSrgb,  false,     false,      true,        4, 4 },
		{ EResourceFormat::BC4Unorm,           "BC4Unorm",         8,              1,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC4Snorm,           "BC4Snorm",         8,              1,        EFormatType::Snorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC5Unorm,           "BC5Unorm",        16,              2,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC5Snorm,           "BC5Snorm",        16,              2,        EFormatType::Snorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC6HS16,            "BC6HS16",         16,              3,        EFormatType::Float,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC6HU16,            "BC6HU16",         16,              3,        EFormatType::Float,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC7Unorm,           "BC7Unorm",        16,              4,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC7UnormSrgb,       "BC7UnormSrgb",    16,              4,        EFormatType::UnormSrgb,  false,     false,      true,        4, 4 },
	};

	static_assert(arraysize(kFormatDescArray) == (uint32_t)EResourceFormat::BC7UnormSrgb + 1, "Format desc table has a wrong size");
}