#include "RHI/Formats.h"
#include "Framework.h"

namespace GS
{
	const FormatDesc kFormatDescArray[] =
	{
		// Format                              Name,        BytesPerBlock    ChannelCount          Type             bDepth,    bStencil,  bCompressed,   CompressionRatioWidth,     CompressionRatioHeight
		{ EResourceFormat::Unknown,            L"Unknown",          0,              0,        EFormatType::Unknown,    false,     false,     false,        1, 1 },
		{ EResourceFormat::R8Unorm,            L"R8Unorm",          1,              1,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R8Snorm,            L"R8Snorm",          1,              1,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Unorm,           L"R16Unorm",         2,              1,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Snorm,           L"R16Snorm",         2,              1,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG8Unorm,           L"RG8Unorm",         2,              2,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG8Snorm,           L"RG8Snorm",         2,              2,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Unorm,          L"RG16Unorm",        4,              2,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Snorm,          L"RG16Snorm",        4,              2,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Unorm,         L"RGB16Unorm",       6,              3,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Snorm,         L"RGB16Snorm",       6,              3,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R24UnormX8,         L"R24UnormX8",       4,              1,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB5A1Unorm,        L"RGB5A1Unorm",      2,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8Unorm,         L"RGBA8Unorm",       4,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8Snorm,         L"RGBA8Snorm",       4,              4,        EFormatType::Snorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB10A2Unorm,       L"RGB10A2Unorm",     4,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB10A2Uint,        L"RGB10A2Uint",      4,              4,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA16Unorm,        L"RGBA16Unorm",      8,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8UnormSrgb,     L"RGBA8UnormSrgb",   4,              4,        EFormatType::UnormSrgb,  false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Float,           L"R16Float",         2,              1,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Float,          L"RG16Float",        4,              2,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Float,         L"RGB16Float",       6,              3,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA16Float,        L"RGBA16Float",      8,              4,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R32Float,           L"R32Float",         4,              1,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R32FloatX32,        L"R32FloatX32",      4,              1,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RG32Float,          L"RG32Float",        8,              2,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB32Float,         L"RGB32Float",      12,              3,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA32Float,        L"RGBA32Float",     16,              4,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R11G11B10Float,     L"R11G11B10Float",   4,              3,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB9E5Float,        L"RGB9E5Float",      4,              3,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R8Int,              L"R8Int",            1,              1,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R8Uint,             L"R8Uint",           1,              1,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Int,             L"R16Int",           2,              1,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R16Uint,            L"R16Uint",          2,              1,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R32Int,             L"R32Int",           4,              1,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::R32Uint,            L"R32Uint",          4,              1,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG8Int,             L"RG8Int",           2,              2,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG8Uint,            L"RG8Uint",          2,              2,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Int,            L"RG16Int",          4,              2,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG16Uint,           L"RG16Uint",         4,              2,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG32Int,            L"RG32Int",          8,              2,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RG32Uint,           L"RG32Uint",         8,              2,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Int,           L"RGB16Int",         6,              3,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB16Uint,          L"RGB16Uint",        6,              3,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB32Int,           L"RGB32Int",        12,              3,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGB32Uint,          L"RGB32Uint",       12,              3,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8Int,           L"RGBA8Int",         4,              4,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA8Uint,          L"RGBA8Uint",        4,              4,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA16Int,          L"RGBA16Int",        8,              4,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA16Uint,         L"RGBA16Uint",       8,              4,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA32Int,          L"RGBA32Int",       16,              4,        EFormatType::Sint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::RGBA32Uint,         L"RGBA32Uint",      16,              4,        EFormatType::Uint,       false,     false,     false,        1, 1 },
		{ EResourceFormat::BGRA8Unorm,         L"BGRA8Unorm",       4,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::BGRA8UnormSrgb,     L"BGRA8UnormSrgb",   4,              4,        EFormatType::UnormSrgb,  false,     false,     false,        1, 1 },
		{ EResourceFormat::BGRX8Unorm,         L"BGRX8Unorm",       4,              4,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::BGRX8UnormSrgb,     L"BGRX8UnormSrgb",   4,              4,        EFormatType::UnormSrgb,  false,     false,     false,        1, 1 },
		{ EResourceFormat::Alpha8Unorm,        L"Alpha8Unorm",      1,              1,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::Alpha32Float,       L"Alpha32Float",     4,              1,        EFormatType::Float,      false,     false,     false,        1, 1 },
		{ EResourceFormat::R5G6B5Unorm,        L"R5G6B5Unorm",      2,              3,        EFormatType::Unorm,      false,     false,     false,        1, 1 },
		{ EResourceFormat::D32Float,           L"D32Float",         4,              1,        EFormatType::Float,       true,     false,     false,        1, 1 },
		{ EResourceFormat::D16Unorm,           L"D16Unorm",         2,              1,        EFormatType::Unorm,       true,     false,     false,        1, 1 },
		{ EResourceFormat::D32FloatS8X24,      L"D32FloatS8X24",    8,              2,        EFormatType::Float,       true,      true,     false,        1, 1 },
		{ EResourceFormat::D24UnormS8,         L"D24UnormS8",       4,              2,        EFormatType::Unorm,       true,      true,     false,        1, 1 },
		{ EResourceFormat::BC1Unorm,           L"BC1Unorm",         8,              3,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC1UnormSrgb,       L"BC1UnormSrgb",     8,              3,        EFormatType::UnormSrgb,  false,     false,      true,        4, 4 },
		{ EResourceFormat::BC2Unorm,           L"BC2Unorm",        16,              4,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC2UnormSrgb,       L"BC2UnormSrgb",    16,              4,        EFormatType::UnormSrgb,  false,     false,      true,        4, 4 },
		{ EResourceFormat::BC3Unorm,           L"BC3Unorm",        16,              4,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC3UnormSrgb,       L"BC3UnormSrgb",    16,              4,        EFormatType::UnormSrgb,  false,     false,      true,        4, 4 },
		{ EResourceFormat::BC4Unorm,           L"BC4Unorm",         8,              1,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC4Snorm,           L"BC4Snorm",         8,              1,        EFormatType::Snorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC5Unorm,           L"BC5Unorm",        16,              2,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC5Snorm,           L"BC5Snorm",        16,              2,        EFormatType::Snorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC6HS16,            L"BC6HS16",         16,              3,        EFormatType::Float,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC6HU16,            L"BC6HU16",         16,              3,        EFormatType::Float,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC7Unorm,           L"BC7Unorm",        16,              4,        EFormatType::Unorm,      false,     false,      true,        4, 4 },
		{ EResourceFormat::BC7UnormSrgb,       L"BC7UnormSrgb",    16,              4,        EFormatType::UnormSrgb,  false,     false,      true,        4, 4 },
	};

	static_assert(arraysize(kFormatDescArray) == (uint32_t)EResourceFormat::BC7UnormSrgb + 1, "Format desc table has a wrong size");
}