#pragma once

#include <algorithm>
#include <array>
#include <cassert>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <functional>
#include <future>
#include <iterator>
#include <limits>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <ostream>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <thread>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>
#include <deque>
#include <time.h>
#include <sys/timeb.h>
#include <io.h>
#include <share.h>
#define _USE_MATH_DEFINES
#include <math.h>

#include <Eigen/Eigen>
#include <nlohmann/json.hpp>
#include <Assimp/Importer.hpp>
#include <Assimp/Exporter.hpp>
#include <Assimp/scene.h>
#include <Assimp/postprocess.h>
#include <Assimp/mesh.h>
#include <Assimp/anim.h>

#include "Common/WindowsFiles.h"
