#pragma once

#include <GSZHU/BasicTypes.h>
#include <GSZHU/ENUM/EShaderVariableType.h>

namespace GSZHU {
    enum BIND_SHADER_RESOURCES_FLAGS : uint32_t {
        BIND_SHADER_RESOURCES_UPDATE_STATIC = (0x01 << SHADER_VARIABLE_TYPE_STATIC),
        BIND_SHADER_RESOURCES_UPDATE_MUTABLE = (0x01 << SHADER_VARIABLE_TYPE_MUTABLE),
        BIND_SHADER_RESOURCES_UPDATE_DYNAMIC = (0x01 << SHADER_VARIABLE_TYPE_DYNAMIC),
        BIND_SHADER_RESOURCES_UPDATE_ALL = (BIND_SHADER_RESOURCES_UPDATE_STATIC 
                                          | BIND_SHADER_RESOURCES_UPDATE_MUTABLE 
                                          | BIND_SHADER_RESOURCES_UPDATE_DYNAMIC),

        BIND_SHADER_RESOURCES_KEEP_EXISTING = 0x08,
        BIND_SHADER_RESOURCES_VERIFY_ALL_RESOLVED = 0x10
    };
}