#pragma once

#include <GSZHU/BasicTypes.h>

namespace GSZHU {
    enum ERESOURCE_STATE : UINT {
        RESOURCE_STATE_UNKNOWN = 0x0000,
        RESOURCE_STATE_UNDEFINED = 0x0001,
        RESOURCE_STATE_VERTEX_BUFFER = 0x0002,
        RESOURCE_STATE_CONSTANT_BUFFER = 0x0004,
        RESOURCE_STATE_INDEX_BUFFER = 0x0008,
        RESOURCE_STATE_RENDER_TARGET = 0x0010,
        RESOURCE_STATE_UNORDERED_ACCESS = 0x0020,
        RESOURCE_STATE_DEPTH_WRITE = 0x0040,
        RESOURCE_STATE_DEPTH_READ = 0x0080,
        RESOURCE_STATE_SHADER_RESOURCE = 0x0100,
        RESOURCE_STATE_STREAM_OUT = 0x0200,
        RESOURCE_STATE_INDIRECT_ARGUMENT = 0x0400,
        RESOURCE_STATE_COPY_DEST = 0x0800,
        RESOURCE_STATE_COPY_SOURCE = 0x1000,
        RESOURCE_STATE_RESOLVE_DEST = 0x2000,
        RESOURCE_STATE_RESOLVE_SOURCE = 0x4000,
        RESOURCE_STATE_PRESENT = 0x8000,
        RESOURCE_STATE_MAX_BIT = 0x8000,

        RESOURCE_STATE_GENERIC_READ = RESOURCE_STATE_VERTEX_BUFFER | RESOURCE_STATE_CONSTANT_BUFFER | RESOURCE_STATE_INDEX_BUFFER |
                                      RESOURCE_STATE_SHADER_RESOURCE | RESOURCE_STATE_INDIRECT_ARGUMENT | RESOURCE_STATE_COPY_SOURCE
    };
}